name = input("What is your name pretty lady?: ")
print("<<<" ,name, ">>>")
print("(((" ,name, ")))")
print("---", name, "---")
print(":) :)", name, ":) :)")
print("###", name, "###")
print("+++", name, "+++")
print("~~~", name, "~~~")
print("===", name, "===")